/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import bd.BdCliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vo.Cliente;
import vo.Produto;


/**
 *
 * @author Rafael
 */
public class CadastroCliente extends javax.swing.JFrame {
    private Cliente C = new Cliente();
    BdCliente bdc = new BdCliente();
    private boolean novo = true;
    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        
    }
    public void telaToCliente(){
         getC().setNome(tNome.getText());
         getC().setTelefone(tTelefone.getText());
         getC().setEndereco(tEndereco.getText());
         getC().setNumero(tNumero.getText());
         getC().setComplemento(tComplemento.getText());
         getC().setBairro(tBairro.getText());
         getC().setCep(tCep.getText());
         getC().setEmail(tEmail.getText());
         getC().setObs(tObs.getText());
         
           }
      private void clienteToTela(){
          tId.setText(getC().getId());
          tNome.setText(getC().getNome());
          tTelefone.setText(getC().getTelefone());
          tEndereco.setText(getC().getEndereco());
          tNumero.setText(getC().getNumero());
          tComplemento.setText(getC().getComplemento());
          tBairro.setText(getC().getBairro());
          tCep.setText(getC().getCep());
          tEmail.setText(getC().getEmail());
          tObs.setText(getC().getObs());

         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tEndereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tBairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tCep = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tObs = new javax.swing.JTextArea();
        tTelefone = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        btnCancela = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tComplemento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        tNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Telefone");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Endereço");

        tEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEnderecoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Número");

        tNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumeroActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Bairro");

        tBairro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBairroActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("CEP");

        tCep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCepActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Email");

        tEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("OBS");

        tObs.setColumns(20);
        tObs.setRows(5);
        jScrollPane1.setViewportView(tObs);

        try {
            tTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tTelefone.setToolTipText("");
        tTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTelefoneActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código");

        tId.setEditable(false);
        tId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdActionPerformed(evt);
            }
        });

        btnCancela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCancela.setText("Sair");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        btnSalva.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalva.setText("Salvar");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Complemento");

        tComplemento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tComplementoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tEmail)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tComplemento)
                            .addComponent(tId)
                            .addComponent(tNome)
                            .addComponent(tCep)
                            .addComponent(tBairro)
                            .addComponent(tNumero)
                            .addComponent(tEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(tTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancela, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnSalva, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeActionPerformed

    private void tEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEnderecoActionPerformed

    private void tNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumeroActionPerformed

    private void tBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBairroActionPerformed

    private void tCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCepActionPerformed

    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailActionPerformed

    private void tTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTelefoneActionPerformed

    private void tIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        // TODO add your handling code here:
        telaToCliente();
            //Verifica se os campos estão preenchidos para então executar a ação
        try{    
        if (isNovo()){
            if(tNome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            } else {
                if(tTelefone.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(tEndereco.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(tNumero.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(tBairro.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }else{
                        String nom = tNome.getText();
                        String fone = tTelefone.getText();
                    try {
                        if (bdc.verificaNome(nom)== true){
                            if (bdc.verificaTelefone(fone)== true){
                                JOptionPane.showMessageDialog(null, "CLIENTE JÁ CADASTRADO", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                                this.dispose();
                            }else{
                                bdc.insere(C);
                                bdc.fecha();
                                JOptionPane.showMessageDialog(null, "CLIENTE CADASTRADO COM SUCESSO", "OPERAÇÃO FINALIZADA", JOptionPane.INFORMATION_MESSAGE); 
                                this.dispose();
                            }
                        }else{
                            bdc.insere(C);
                            bdc.fecha();
                            JOptionPane.showMessageDialog(null, "CLIENTE CADASTRADO COM SUCESSO", "OPERAÇÃO FINALIZADA", JOptionPane.INFORMATION_MESSAGE); 
                            this.dispose();
                        }       }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "SOMENTE NÚMEROS", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                                  
     
    
      
                    }   catch (Exception ex) {
                            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    }
                }
                }
            }
        } else {
            if(tNome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            } else {
                if(tTelefone.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(tEndereco.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(tNumero.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(tBairro.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }else{
                            bdc.atualiza(C);
                            bdc.fecha();
                            JOptionPane.showMessageDialog(null, "CLIENTE ATUALIZADO COM SUCESSO", "OPERAÇÃO FINALIZADA", JOptionPane.INFORMATION_MESSAGE); 
                            this.dispose();
                    }
                    }
                }
                }
            }
        }
            
        
           }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "SOMENTE NÚMEROS", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }                             
    }//GEN-LAST:event_btnSalvaActionPerformed

    private void tComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tComplementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBairro;
    private javax.swing.JTextField tCep;
    private javax.swing.JTextField tComplemento;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tEndereco;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tNumero;
    private javax.swing.JTextArea tObs;
    private javax.swing.JFormattedTextField tTelefone;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the C
     */
    public Cliente getC() {
        return C;
    }

    /**
     * @param C the C to set
     */
    public void setC(Cliente C) {
        this.C = C;
        clienteToTela();
    }

    /**
     * @return the novo
     */
    public boolean isNovo() {
        return novo;
    }

    /**
     * @param novo the novo to set
     */
    public void setNovo(boolean novo) {
        this.novo = novo;
    }

    void setP(Produto localizaId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
