/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import bd.BdLanche;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vo.Lanche;

/**
 *
 * @author Rafael
 */
public class CadastroLanche extends javax.swing.JFrame {
    private Lanche L = new Lanche();
    BdLanche bdl = new BdLanche();
    private boolean novo = true;
    private String preco;
    private double precofinal;
    private boolean erro=false;
    /**
     * Creates new form CadastroLanche
     */
    public CadastroLanche() {
        initComponents();
        
    }
public void telaToLanche(){
         L.setNome(tNome.getText());
         L.setPreco(Double.parseDouble(preco));      
           }
      private void produtoToTela(){
          tIdlanche.setText(Integer.toString(L.getIdlanche()));
          tNome.setText(L.getNome());
          tPreco.setText(Double.toString(L.getPreco()));
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tIdlanche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSalva = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        tPreco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código");

        tIdlanche.setEditable(false);
        tIdlanche.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tIdlanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdlancheActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        tNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Preço");

        btnSalva.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalva.setText("Salvar");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        btnCancela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCancela.setText("Sair");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        tPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tPreco.setToolTipText("Insira o valor com casas decimais");
        tPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tIdlanche, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tIdlanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(tPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tIdlancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdlancheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdlancheActionPerformed

    private void tNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        // TODO add your handling code here:
        erro = false;
        try{
        preco = tPreco.getText();
        preco = preco.replaceAll(",", ".");  
        precofinal = Double.parseDouble(preco);
        }catch (NumberFormatException e){
            erro = true;
            JOptionPane.showMessageDialog(null, "SOMENTE NÚMEROS", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

                }
                    if(erro == true){
                        
                    System.out.println("ERRO");
    }//GEN-LAST:event_btnSalvaActionPerformed
                    else{
                    salvar();
                     System.out.println("SUCESSO");
                    }
                   
    }
    
    private void salvar(){
        telaToLanche();
    if(isNovo()){
                    
                    if(tNome.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "PREENCHA TODOS OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                        
                    }else{
                        
                            String nom = tNome.getText();
                            try {
                                if (bdl.verificaNome(nom)== true){
                                    JOptionPane.showMessageDialog(null, "PRODUTO JÁ CADASTRADO", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                                }else{
                                    bdl.insere(L);
                                    bdl.fecha();
                                    JOptionPane.showMessageDialog(null, "PRODUTO CADASTRADO COM SUCESSO", "OPERAÇÃO FINALIZADA", JOptionPane.INFORMATION_MESSAGE);
                                    this.dispose();
                                }  }catch (Exception ex) {
                                Logger.getLogger(CadastroLanche.class.getName()).log(Level.SEVERE, null, ex);
                            }
                    }
                    
                }else{
                if(tNome.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "PREENCHA TODOS OS CAMPOS CORRETAMENTE", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                        
                    }else{
                       
                            
                                
                                    bdl.atualiza(L);
                                    bdl.fecha();
                                    JOptionPane.showMessageDialog(null, "PRODUTO ATUALIZADO COM SUCESSO", "OPERAÇÃO FINALIZADA", JOptionPane.INFORMATION_MESSAGE);
                                    this.dispose();
                                      

                                
                        }
                    }
    }
    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void tPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLanche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tIdlanche;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tPreco;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the P
     */
    public Lanche getL() {
        return L;
    }

    /**
     * @param P the P to set
     */
    public void setP(Lanche P) {
        this.setL(L);
        produtoToTela();
    }

    /**
     * @return the novo
     */
    public boolean isNovo() {
        return novo;
    }

    /**
     * @param novo the novo to set
     */
    public void setNovo(boolean novo) {
        this.novo = novo;
    }

    /**
     * @param L the L to set
     */
    public void setL(Lanche L) {
        this.L = L;
    }
}
