/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import bd.BdCliente;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Iterator;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;
import vo.Cliente;



/**
 *
 * @author Rafael
 */
public class TabelaClientes extends javax.swing.JFrame {
    
    /**
     * Creates new form TabelaClientes
     */
    
    BdCliente bd;

    
    
    public TabelaClientes() {
        initComponents();
       // setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        preencheTabela();

        
    }
    
     
  
 private void preencheTabela() {
      DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
        int i = modelo.getRowCount();
        while (i--> 0) {
            modelo.removeRow(i);
        }
        bd = new BdCliente();
        List c = bd.retornaTabela();
        for (Iterator it = c.iterator(); it.hasNext();) {
            Cliente C = (Cliente) it.next();
            modelo.addRow(new Object[]{C.getNome(), C.getTelefone(), C.getEndereco(), C.getNumero(), C.getComplemento(), C.getBairro(), C.getCep(), C.getEmail(), C.getObs()});

        }
        bd.fecha();
    }

     private void preencheTabelaPesquisaNome() {
      DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
        int i = modelo.getRowCount();
        while (i--> 0) {
            modelo.removeRow(i);
        }
        bd = new BdCliente();
        List c = bd.pesquisaNomeTabela(tFiltro.getText());
        for (Iterator it = c.iterator(); it.hasNext();) {
            Cliente C = (Cliente) it.next();
            modelo.addRow(new Object[]{C.getNome(), C.getTelefone(), C.getEndereco(), C.getNumero(), C.getComplemento(), C.getBairro(), C.getCep(), C.getEmail(), C.getObs()});

        }
        bd.fecha();
    }
     private void preencheTabelaPesquisaTelefone() {
      DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
        int i = modelo.getRowCount();
        while (i--> 0) {
            modelo.removeRow(i);
        }
        bd = new BdCliente();
        List c = bd.pesquisaTelefoneTabela(tFiltroTel.getText());
        for (Iterator it = c.iterator(); it.hasNext();) {
            Cliente C = (Cliente) it.next();
            modelo.addRow(new Object[]{C.getNome(), C.getTelefone(), C.getEndereco(), C.getNumero(), C.getComplemento(), C.getBairro(), C.getCep(), C.getEmail(), C.getObs()});

        }
        bd.fecha();
    }
     


 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        btnExibirTudo2 = new javax.swing.JButton();
        btnExibirTudo1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tFiltroTel = new javax.swing.JTextField();
        tFiltro = new javax.swing.JTextField();
        btnExibirTudo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "Endereço", "Núm", "Complemento", "Bairro", "CEP", "Email", "OBS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        btnExibirTudo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExibirTudo2.setText("Atualizar registros");
        btnExibirTudo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirTudo2ActionPerformed(evt);
            }
        });

        btnExibirTudo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExibirTudo1.setText("Cadastrar novo cliente");
        btnExibirTudo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirTudo1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Buscar por nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Buscar por telefone");

        tFiltroTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tFiltroTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFiltroTelActionPerformed(evt);
            }
        });
        tFiltroTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFiltroTelKeyReleased(evt);
            }
        });

        tFiltro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFiltroActionPerformed(evt);
            }
        });
        tFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFiltroKeyReleased(evt);
            }
        });

        btnExibirTudo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExibirTudo3.setText("Sair do módulo");
        btnExibirTudo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirTudo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1162, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnExibirTudo2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnExibirTudo1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tFiltroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnExibirTudo3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnExibirTudo1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnExibirTudo2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tFiltroTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(btnExibirTudo3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            Point p = evt.getPoint();
            int row = jTableClientes.rowAtPoint(p);
            DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
            String tel =(String)  modelo.getValueAt(row, 1);
            CadastroCliente t = new CadastroCliente();
            t.setNovo(false);
            bd = new BdCliente();
            t.setC(bd.localizaTel(tel));
            bd.fecha();
            t.setVisible(true);
        }
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void btnExibirTudo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirTudo2ActionPerformed
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_btnExibirTudo2ActionPerformed

    private void btnExibirTudo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirTudo1ActionPerformed
        // TODO add your handling code here:
        CadastroCliente t = new CadastroCliente();
        t.setVisible(true);
    }//GEN-LAST:event_btnExibirTudo1ActionPerformed

    private void tFiltroTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFiltroTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFiltroTelActionPerformed

    private void tFiltroTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFiltroTelKeyReleased
        // TODO add your handling code here:
        preencheTabelaPesquisaTelefone();
    }//GEN-LAST:event_tFiltroTelKeyReleased

    private void tFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFiltroActionPerformed

    private void tFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFiltroKeyReleased
        // TODO add your handling code here:
        preencheTabelaPesquisaNome();
    }//GEN-LAST:event_tFiltroKeyReleased

    private void btnExibirTudo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirTudo3ActionPerformed
        // TODO add your handling code here:
        //timer.cancel();
        this.dispose();
    }//GEN-LAST:event_btnExibirTudo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaClientes().setVisible(true);
            }
        });
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExibirTudo1;
    private javax.swing.JButton btnExibirTudo2;
    private javax.swing.JButton btnExibirTudo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField tFiltro;
    private javax.swing.JTextField tFiltroTel;
    // End of variables declaration//GEN-END:variables
}
